events {}

http {
    server {
        listen 80;

        location /app/ {
            proxy_pass http://frontend:80/;
        }

        location /api/ {
            proxy_pass http://backend:5000/;
        }

        location /legacy/ {
            proxy_pass http://lamp:80/;
        }
    }
}
