server {
    listen 80;

    location /app/ {
        proxy_pass http://mern-frontend/;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://mern-backend:5000/;
    }

    location /legacy/ {
        proxy_pass http://lamp-apache/;
    }
}
